# Generated by Django 2.2.4 on 2019-09-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190902_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.PositiveSmallIntegerField(choices=[(1, 'VOTE UP'), (-1, 'VOTE DOWN')], null=True, verbose_name='Vote'),
        ),
    ]
